language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

env:
  - LIBMEMCACHED_VERSION='0.44'
  - LIBMEMCACHED_VERSION='0.53'
  - LIBMEMCACHED_VERSION='1.0.8'

notifications:
  irc:
    channels:
      - "chat.freenode.net#sendapatch"
    on_success: change
    on_failure: change

before_install:
  # Default travis-ci libmemcached is 0.44 (ubuntu precise). If we need a
  # higher version, add in the appropriate ppa. The newer package will upgrade
  # the desired revision when we do a `apt-get install libmemcached-dev`.
  - sh -c "if [ $LIBMEMCACHED_VERSION = '1.0.8' ] ; then sudo add-apt-repository ppa:plewis-m/ppa-libmemcached -y; fi"
  - sh -c "if [ $LIBMEMCACHED_VERSION = '0.53' ] ; then sudo add-apt-repository ppa:plewis-m/libmemcached0.5x -y; fi"
  - sudo apt-get update -qq
  - sudo apt-get install memcached
  - sudo service memcached start
  - sudo apt-get install libmemcached-dev
  - echo "stats settings" | nc localhost 11211

install: python setup.py install

before_script:
  - pip install nose

script: python bin/runtests.py
